#ifndef POKEDB_H
#define POKEDB_H

#include "typedb.h"
#include <string>
using namespace std;

class type;

class pokeStat {
 public:
  pokeStat(unsigned n, string nm, unsigned h, unsigned a, 
	   unsigned def, unsigned splatk, unsigned spldef, unsigned speed, string t1, string t2);
  pokeStat(const pokeStat &old);
  unsigned getNum();
  string getName();
  type getType1();
  type getType2();
  unsigned getBaseHP();
  unsigned getBaseAtk();
  unsigned getBaseDef();
  unsigned getBaseSplAtk();
  unsigned getBaseSplDef();
  unsigned getBaseSpeed();
  
 private:
  string name;
  unsigned object_id;
  type m_type1;
  type m_type2;
  unsigned base_hp;
  unsigned base_atk;
  unsigned base_def;
  unsigned base_splatk;
  unsigned base_spldef;
  unsigned base_speed;
};

struct bulbasaur : public pokeStat { bulbasaur(); };
struct ivysaur : public pokeStat { ivysaur(); };
struct venusaur : public pokeStat { venusaur(); };
struct charmander : public pokeStat { charmander(); };
struct charmeleon : public pokeStat { charmeleon(); };
struct charizard : public pokeStat { charizard(); };
struct squirtle : public pokeStat { squirtle(); };
struct wartortle : public pokeStat { wartortle(); };
struct blastoise : public pokeStat { blastoise(); };
struct caterpie : public pokeStat { caterpie(); };
struct metapod : public pokeStat { metapod(); };
struct butterfree : public pokeStat { butterfree(); };
struct weedle : public pokeStat { weedle(); };
struct kakuna : public pokeStat { kakuna(); };
struct beedrill : public pokeStat { beedrill(); };
struct pidgey : public pokeStat { pidgey(); };
struct pidgeotto : public pokeStat { pidgeotto(); };
struct pidgeot : public pokeStat { pidgeot(); };
struct rattata : public pokeStat { rattata(); };
struct raticate : public pokeStat { raticate(); };
struct spearow : public pokeStat { spearow(); };
struct fearow : public pokeStat { fearow(); };
struct ekans : public pokeStat { ekans(); };
struct arbok : public pokeStat { arbok(); };
struct pikachu : public pokeStat { pikachu(); };
struct raichu : public pokeStat { raichu(); };
struct sandshrew : public pokeStat { sandshrew(); };
struct sandslash : public pokeStat { sandslash(); };
struct nidoranF : public pokeStat { nidoranF(); };
struct nidorina : public pokeStat { nidorina(); };
struct nidoqueen : public pokeStat { nidoqueen(); };
struct nidoranM : public pokeStat { nidoranM(); };
struct nidorino : public pokeStat { nidorino(); };
struct nidoking : public pokeStat { nidoking(); };
struct clefairy : public pokeStat { clefairy(); };
struct clefable : public pokeStat { clefable(); };
struct vulpix : public pokeStat { vulpix(); };
struct ninetales : public pokeStat { ninetales(); };
struct jigglypuff : public pokeStat { jigglypuff(); };
struct wigglytuff : public pokeStat { wigglytuff(); };
struct zubat : public pokeStat { zubat(); };
struct golbat : public pokeStat { golbat(); };
struct oddish : public pokeStat { oddish(); };
struct gloom : public pokeStat { gloom(); };
struct vileplume : public pokeStat { vileplume(); };
struct paras : public pokeStat { paras(); };
struct parasect : public pokeStat { parasect(); };
struct venonat : public pokeStat { venonat(); };
struct venomoth : public pokeStat { venomoth(); };
struct diglett : public pokeStat { diglett(); };
struct dugtrio : public pokeStat { dugtrio(); };
struct meowth : public pokeStat { meowth(); };
struct persian : public pokeStat { persian(); };
struct psyduck : public pokeStat { psyduck(); };
struct golduck : public pokeStat { golduck(); };
struct mankey : public pokeStat { mankey(); };
struct primeape : public pokeStat { primeape(); };
struct growlithe : public pokeStat { growlithe(); };
struct arcanine : public pokeStat { arcanine(); };
struct poliwag : public pokeStat { poliwag(); };
struct poliwhirl : public pokeStat { poliwhirl(); };
struct poliwrath : public pokeStat { poliwrath(); };
struct abra : public pokeStat { abra(); };
struct kadabra : public pokeStat { kadabra(); };
struct alakazam : public pokeStat { alakazam(); };
struct machop : public pokeStat { machop(); };
struct machoke : public pokeStat { machoke(); };
struct machamp : public pokeStat { machamp(); };
struct bellsprout : public pokeStat { bellsprout(); };
struct weepinbell : public pokeStat { weepinbell(); };
struct victreebel : public pokeStat { victreebel(); };
struct tentacool : public pokeStat { tentacool(); };
struct tentacruel : public pokeStat { tentacruel(); };
struct geodude : public pokeStat { geodude(); };
struct graveler : public pokeStat { graveler(); };
struct golem : public pokeStat { golem(); };
struct ponyta : public pokeStat { ponyta(); };
struct rapidash : public pokeStat { rapidash(); };
struct slowpoke : public pokeStat { slowpoke(); };
struct slowbro : public pokeStat { slowbro(); };
struct magnemite : public pokeStat { magnemite(); };
struct magneton : public pokeStat { magneton(); };
struct farfetchD : public pokeStat { farfetchD(); };
struct doduo : public pokeStat { doduo(); };
struct dodrio : public pokeStat { dodrio(); };
struct seel : public pokeStat { seel(); };
struct dewgong : public pokeStat { dewgong(); };
struct grimer : public pokeStat { grimer(); };
struct muk : public pokeStat { muk(); };
struct shellder : public pokeStat { shellder(); };
struct cloyster : public pokeStat { cloyster(); };
struct gastly : public pokeStat { gastly(); };
struct haunter : public pokeStat { haunter(); };
struct gengar : public pokeStat { gengar(); };
struct onix : public pokeStat { onix(); };
struct drowzee : public pokeStat { drowzee(); };
struct hypno : public pokeStat { hypno(); };
struct krabby : public pokeStat { krabby(); };
struct kingler : public pokeStat { kingler(); };
struct voltorb : public pokeStat { voltorb(); };
struct electrode : public pokeStat { electrode(); };
struct exeggcute : public pokeStat { exeggcute(); };
struct exeggutor : public pokeStat { exeggutor(); };
struct cubone : public pokeStat { cubone(); };
struct marowak : public pokeStat { marowak(); };
struct hitmonlee : public pokeStat { hitmonlee(); };
struct hitmonchan : public pokeStat { hitmonchan(); };
struct lickitung : public pokeStat { lickitung(); };
struct koffing : public pokeStat { koffing(); };
struct weezing : public pokeStat { weezing(); };
struct rhyhorn : public pokeStat { rhyhorn(); };
struct rhydon : public pokeStat { rhydon(); };
struct chansey : public pokeStat { chansey(); };
struct tangela : public pokeStat { tangela(); };
struct kangaskhan : public pokeStat { kangaskhan(); };
struct horsea : public pokeStat { horsea(); };
struct seadra : public pokeStat { seadra(); };
struct goldeen : public pokeStat { goldeen(); };
struct seaking : public pokeStat { seaking(); };
struct staryu : public pokeStat { staryu(); };
struct starmie : public pokeStat { starmie(); };
struct mrMime : public pokeStat { mrMime(); };
struct scyther : public pokeStat { scyther(); };
struct jynx : public pokeStat { jynx(); };
struct electabuzz : public pokeStat { electabuzz(); };
struct magmar : public pokeStat { magmar(); };
struct pinsir : public pokeStat { pinsir(); };
struct tauros : public pokeStat { tauros(); };
struct magikarp : public pokeStat { magikarp(); };
struct gyarados : public pokeStat { gyarados(); };
struct lapras : public pokeStat { lapras(); };
struct ditto : public pokeStat { ditto(); };
struct eevee : public pokeStat { eevee(); };
struct vaporeon : public pokeStat { vaporeon(); };
struct jolteon : public pokeStat { jolteon(); };
struct flareon : public pokeStat { flareon(); };
struct porygon : public pokeStat { porygon(); };
struct omanyte : public pokeStat { omanyte(); };
struct omastar : public pokeStat { omastar(); };
struct kabuto : public pokeStat { kabuto(); };
struct kabutops : public pokeStat { kabutops(); };
struct aerodactyl : public pokeStat { aerodactyl(); };
struct snorlax : public pokeStat { snorlax(); };
struct articuno : public pokeStat { articuno(); };
struct zapdos : public pokeStat { zapdos(); };
struct moltres : public pokeStat { moltres(); };
struct dratini : public pokeStat { dratini(); };
struct dragonair : public pokeStat { dragonair(); };
struct dragonite : public pokeStat { dragonite(); };
struct mewtwo : public pokeStat { mewtwo(); };
struct mew : public pokeStat { mew(); };

#endif
